
version: '3.8'

services:
  safa-water:
    build:
      context: .
    container_name: safa_water_system
    ports:
      - "8080:80"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
